### ISSUE TITLE
Update npm package for Alfred 4

### ISSUE THREAD

**Issue by kknopper** [kbshl/alfred-vscode#19]
Recently just updated Alfred for its version 4 release. When I tried npm install it failed - it looks like the preferences path is different with the new release

**Comment by kisnows** [comment]
Same with you.
```
{ Error: Command failed: alfred-link
Error: Alfred preferences not found at location /Users/xxx/Library/Preferences/com.runningwithcrayons.Alfred-Preferences-3.plist
    at pathExists.then.exists (/usr/local/lib/node_modules/alfred-vscode/node_modules/resolve-alfred-prefs/index.js:15:10)


    at makeError (/usr/local/lib/node_modules/alfred-vscode/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/usr/local/lib/node_modules/alfred-vscode/node_modules/execa/index.js:278:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 1,
  stdout: '',
  stderr:
   'Error: Alfred preferences not found at location /Users/xxx/Library/Preferences/com.runningwithcrayons.Alfred-Preferences-3.plist\n    at pathExists.then.exists (/usr/local/lib/node_modules/alfred-vscode/node_modules/resolve-alfred-prefs/index.js:15:10)\n',
  failed: true,
  signal: null,
  cmd: 'alfred-link',
  timedOut: false,
  killed: false }
```

**Comment by Liquidmantis** [comment]
This is an issue with a dependency.
https://github.com/sindresorhus/alfy/issues/110

**Comment by LitoMore** [comment]
Now Alfy supports Alfred 4, alfred-link has been released a patch update to add support for Alfred 4. Just update your dependencies to get it to work. 😄
