### ISSUE TITLE
vsc doesn't work?

### ISSUE THREAD

**Issue by ringcrl** [kbshl/alfred-vscode#9]
![image](https://user-images.githubusercontent.com/16740021/42120574-1c87aba4-7c50-11e8-908d-f181c4b968b0.png)

Find it doesn't list my project when i typed vsc...

**Comment by Dec-F** [comment]
> ![image](https://user-images.githubusercontent.com/16740021/42120574-1c87aba4-7c50-11e8-908d-f181c4b968b0.png)
> 
> Find it doesn't list my project when i typed vsc...

Open debug to see the debugging information, one possibility is that the `node` path can not be found. For example, if you use the version management tool like `nvm`, it will cause the executable to be found in `/usr/local/bin/node`. In this case, you run `which node` to check the real `node `path, and then modify it in the workflow config

**Comment by kbshl** [comment]
@Dec-F thanks for the answer 🤗 @ringcrl, has this solved your issue?

**Comment by kbshl** [comment]
I'm closing this issue due to inactivity. Feel free to open a new one if the issue reappears

**Comment by intafon** [comment]
Debug below -- I am running nvm, but adding nodePath env var doesn't seem to do the trick. I set nodePath in the env vars to /Users/me/.nvm/versions/node/v11.14.0/bin/node, but it doesn't seem to pick up (and not sure if this is why I'm getting the error on async or not..):

Starting debug for 'Visual Studio Code'

[2019-05-08 09:45:15][ERROR: input.scriptfilter] Code 1: /Users/me/.nvm/versions/node/v6.11.1/lib/node_modules/alfred-vscode/index.js:4
(async () => {
       ^
SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
